server:
  port: 7070

spring:
  application:
    name: point-service

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://admin:kkk@localhost:5050/eureka/