spring:
  application:
    name: mobil-api

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: false
    metadata-map:
      my-meta: yangMeta
  client:
    service-url:
      defaultZone: http://admin:kkk@localhost:5050/eureka/

feign:
  hystrix:
    enabled: true

logging:
  level:
    root: info